version: '3'
services:
  app:
    build: .
    image: node:11
    working_dir: /dist
    command: bash -c "npm run test && npm run start"
    ports:
      - 3000:3000
      volumes:
        - type: volume
          source: backendData
          target: /dist/files
  
  volumes:
    backendData:
  