version: '3.4'
services:
  prod_frontend:
    build:
      context: ../../
      dockerfile: .docker/prod/Dockerfile
    restart: always
    container_name: prod_frontend
    ports:
      - "4000:4000"

  prod_backend:
    build: ../../../
    restart: always
    container_name: prod_backend
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: imageData
        target: /home/node/imageData

volumes:
  imageData: