version: '3.4'
services:
  dev_frontend:
    build:
      context: ../../
      dockerfile: .docker/dev/Dockerfile
    container_name: dev_frontend
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ../../
        target: /home/node/

  dev_backend:
    build: ../../../
    container_name: dev_backend
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: imageData
        target: /home/node/imageData

volumes:
  imageData: